# Generated by Django 5.2.17 on 2026-09-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='last_member_sequence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
