# Generated by Django 5.2.17 on 2026-09-11 21:35

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_church_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('church'), name='unique_branch_name_per_church'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('church'), name='unique_region_name_per_church'),
        ),
    ]
