# Generated by Django 5.2.17 on 2026-09-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_ministryrole_options'),
        ('tenants', '0006_church_registration_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='pastors',
            field=models.ManyToManyField(blank=True, help_text="Members who receive this region's attendance statistics by SMS after each service.", related_name='pastor_of_regions', to='members.member'),
        ),
    ]
