# Generated by Django 5.2.17 on 2026-09-14 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_scope_branch_alter_user_scope_type'),
        ('members', '0008_remove_member_branch'),
        ('services', '0004_remove_service_branch'),
        ('tenants', '0007_region_pastors'),
        ('visitors', '0002_remove_visitor_branch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
