# Generated by Django 5.2.17 on 2026-09-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_church_region_pastor_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='registration_heading',
            field=models.CharField(blank=True, help_text='Large heading beside the registration form, for example "Building Lives, Changing Nations". Leave blank to show "Welcome to" and the church name.', max_length=80),
        ),
        migrations.AddField(
            model_name='church',
            name='registration_image',
            field=models.ImageField(blank=True, help_text='Optional wide photo for the registration page. Without one, the church colours are used.', null=True, upload_to='church_registration/'),
        ),
        migrations.AddField(
            model_name='church',
            name='registration_message',
            field=models.CharField(blank=True, help_text='Short welcome message under the heading. Leave blank for a general welcome.', max_length=240),
        ),
    ]
