# Generated by Django 5.2.17 on 2026-09-21 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_church_usher_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='absence_alert_after',
            field=models.PositiveSmallIntegerField(default=3, help_text='Checked each time a service closes. 0 turns absence alerts off.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Alert pastors after this many missed services in a row'),
        ),
    ]
