# Generated by Django 5.2.17 on 2026-09-14 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_time_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='branch',
        ),
    ]
