# Generated by Django 5.2.17 on 2026-09-03 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='tenants.church'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_tesmus_staff',
            field=models.BooleanField(default=False),
        ),
    ]
