# Generated by Django 5.2.17 on 2026-09-03 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_church_alter_user_is_tesmus_staff'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scope_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scoped_users', to='tenants.branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='scope_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scoped_users', to='tenants.region'),
        ),
        migrations.AddField(
            model_name='user',
            name='scope_type',
            field=models.CharField(choices=[('church', 'Church-wide'), ('region', 'Region'), ('branch', 'Branch'), ('none', 'None')], default='none', max_length=10),
        ),
    ]
