# Generated by Django 5.2.17 on 2026-09-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_branch_scope_to_none'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='scope_branch',
        ),
        migrations.AlterField(
            model_name='user',
            name='scope_type',
            field=models.CharField(choices=[('church', 'Church-wide'), ('region', 'Region'), ('none', 'None')], default='none', max_length=10),
        ),
    ]
