# Generated by Django 5.2.17 on 2026-09-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_scope_branch_alter_user_scope_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_usher',
            field=models.BooleanField(default=False, help_text='Can only use the usher check-in screen for their church, and nothing else.'),
        ),
    ]
