# Generated by Django 5.2.17 on 2026-09-14 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_is_usher'),
        ('members', '0008_remove_member_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='member',
            field=models.OneToOneField(blank=True, help_text='The member record of the person who uses this sign-in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='members.member'),
        ),
    ]
