"""
Django settings for churchflow_platform project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Every setting that differs between a developer's PC and the live server is
# read from the environment (or a .env file beside manage.py). See .env.example.
load_dotenv(BASE_DIR / '.env')


def env_bool(name, default=False):
    value = os.getenv(name, '').strip().lower()
    if not value:
        return default
    return value in ('1', 'true', 'yes', 'on')


def env_list(name):
    """A comma-separated setting, e.g. "churchflow.co.ke,www.churchflow.co.ke"."""
    return [item.strip() for item in os.getenv(name, '').split(',') if item.strip()]


def env_int(name, default):
    value = os.getenv(name, '').strip()
    try:
        return int(value) if value else default
    except ValueError:
        raise ImproperlyConfigured(f'{name} must be a whole number, not "{value}".')


# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
# Off unless DJANGO_DEBUG=True, so a live server never shows error details by accident.
DEBUG = env_bool('DJANGO_DEBUG')

SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', '').strip()
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured('Set DJANGO_SECRET_KEY (a long random value) before running without DJANGO_DEBUG=True.')
    # Development only: this key is public, so it must never be used on the live server.
    SECRET_KEY = 'django-insecure-1=*d(twfc#gbh#s56t0dlibi8j27@)k=_u_*h-a+*4*ytx_7pk'

# The domain names the site is served on. While debugging, localhost is allowed automatically.
ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS')
# Full addresses (with https://) that forms may be posted from, when behind a proxy or load balancer.
CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS')

# Render tells the app its own address (e.g. tesmus-churchflow.onrender.com), so
# the site works there before a custom domain is added.
RENDER_EXTERNAL_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME', '').strip()
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')


# Application definition

INSTALLED_APPS = [
    # Must come before django.contrib.admin so its admin templates are used.
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'tenants',
    'members',
    'visitors',
    'services',
    'attendance',
    'messaging',
    'pastoral',
    'analytics',
    'audit',
    'dashboard',
    'notifications',
]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves the collected static files (CSS, JS, images) on the live server.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # Keeps usher accounts on the usher check-in screen only.
    'accounts.middleware.UsherAccessMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'churchflow_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'churchflow_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# PostgreSQL whenever POSTGRES_DB is set. A PC without it keeps using the local
# SQLite file, which is for development only and refused on the live server.
if os.getenv('POSTGRES_DB', '').strip():
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB').strip(),
            'USER': os.getenv('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', ''),
            'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
            # Reuse connections for a minute instead of opening one per page,
            # checking first that a reused connection is still alive.
            'CONN_MAX_AGE': env_int('POSTGRES_CONN_MAX_AGE', 60),
            'CONN_HEALTH_CHECKS': True,
            'OPTIONS': {'sslmode': os.getenv('POSTGRES_SSLMODE', 'prefer')},
        }
    }
elif DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    raise ImproperlyConfigured('Set POSTGRES_DB (and the other POSTGRES_* settings) for the live server.')


# Shared cache that survives restarts and works across several server
# processes (check-in attempt limits, notification refresh). Create its table
# once per database with: python manage.py createcachetable
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'churchflow_cache',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / 'static']
# Where "python manage.py collectstatic" gathers files for the web server on the live site.
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

STORAGES = {
    # Uploaded church logos and registration photos. Saved in the media folder
    # on a PC; on the live server they go to Cloudinary (below), because
    # Render wipes files saved on the server at every deploy.
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    # Compressed files with a fingerprint in each name, so browsers can cache
    # them safely; plain files while developing.
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage' if DEBUG
        else 'churchflow_platform.storage.ForgivingManifestStaticFilesStorage',
    },
}
# Set on the live server from the Cloudinary dashboard ("API environment variable").
if os.getenv('CLOUDINARY_URL', '').strip():
    STORAGES['default'] = {'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage'}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'

# HTTPS protections for the live server. The site is expected to sit behind a
# web server or proxy (e.g. Nginx) that handles the certificate and tells Django
# the original request was HTTPS.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = env_bool('DJANGO_SECURE_SSL_REDIRECT', default=True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Start small; raise to 31536000 (one year) once HTTPS is confirmed working everywhere.
    SECURE_HSTS_SECONDS = env_int('DJANGO_SECURE_HSTS_SECONDS', 3600)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS')

# Warnings and errors (including crashes on the live server) are printed, so
# they appear in Render's Logs tab instead of being lost.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {'console': {'class': 'logging.StreamHandler'}},
    'root': {'handlers': ['console'], 'level': os.getenv('DJANGO_LOG_LEVEL', 'WARNING')},
}

# Photo beside the public self-registration form, for churches that have not
# uploaded their own registration image. Loaded from Unsplash (free Unsplash
# License): https://unsplash.com/photos/a-cross-on-a-hill-with-a-sunset-in-the-background-rsEzCapRG74
# Set to '' to show the church's colours instead.
SELF_REGISTRATION_DEFAULT_IMAGE = (
    'https://images.unsplash.com/photo-1632257132513-ca29158c154c?auto=format&fit=crop&w=1400&q=80'
)


# Django admin (/admin/) appearance, using Jazzmin in the Tesmus brand colours
# (charcoal #2C2C2C, gold #C6A16A, cream #F5EEE4). Church dashboards, sign-in
# pages and the public site do not use these settings.
# https://django-jazzmin.readthedocs.io/configuration/
JAZZMIN_SETTINGS = {
    'site_title': 'Tesmus ChurchFlow Admin',
    'site_header': 'Tesmus ChurchFlow',
    'site_brand': 'Tesmus ChurchFlow',
    'site_logo': 'images/branding/tesmus-logo.png',
    'login_logo': 'images/branding/tesmus-logo.png',
    'site_logo_classes': 'tesmus-admin-logo',
    'site_icon': 'images/branding/tesmus-logo.png',
    'welcome_sign': 'Sign in to manage Tesmus ChurchFlow',
    'copyright': 'Tesmus Technologies Limited',
    'topmenu_links': [
        {'name': 'Admin home', 'url': 'admin:index'},
        {'name': 'View site', 'url': 'public_home', 'new_window': True},
    ],
    'show_sidebar': True,
    'navigation_expanded': True,
    'order_with_respect_to': [
        'tenants', 'accounts', 'members', 'visitors', 'services', 'attendance',
        'messaging', 'pastoral', 'notifications', 'audit', 'auth',
    ],
    'icons': {
        'tenants': 'fas fa-church',
        'tenants.church': 'fas fa-church',
        'tenants.region': 'fas fa-map-marker-alt',
        'accounts': 'fas fa-user-shield',
        'accounts.user': 'fas fa-user',
        'auth': 'fas fa-users-cog',
        'auth.group': 'fas fa-users',
        'members': 'fas fa-address-book',
        'members.member': 'fas fa-user-friends',
        'members.ministryrole': 'fas fa-hands-helping',
        'visitors': 'fas fa-door-open',
        'visitors.visitor': 'fas fa-user-plus',
        'services': 'fas fa-calendar-alt',
        'services.service': 'fas fa-calendar-alt',
        'attendance': 'fas fa-clipboard-check',
        'attendance.attendance': 'fas fa-clipboard-check',
        'messaging': 'fas fa-comment-dots',
        'messaging.smsconfiguration': 'fas fa-sliders-h',
        'messaging.smstemplate': 'fas fa-file-alt',
        'messaging.smsmessage': 'fas fa-sms',
        'pastoral': 'fas fa-hand-holding-heart',
        'pastoral.pastoralfollowup': 'fas fa-hand-holding-heart',
        'notifications': 'fas fa-bell',
        'notifications.notification': 'fas fa-bell',
        'audit': 'fas fa-history',
        'audit.auditlog': 'fas fa-history',
    },
    'default_icon_parents': 'fas fa-folder',
    'default_icon_children': 'fas fa-circle',
    'related_modal_active': False,
    'custom_css': 'css/admin-tesmus.css',
    'show_ui_builder': False,
    # One page per form, as before, so no field is hidden behind a tab.
    'changeform_format': 'single',
}

JAZZMIN_UI_TWEAKS = {
    'theme': 'default',
    'default_theme_mode': 'light',
    'navbar': 'navbar-white navbar-light',
    'sidebar': 'sidebar-dark-primary',
    'accent': 'accent-primary',
    'navbar_fixed': True,
    'sidebar_fixed': True,
    'sidebar_nav_child_indent': True,
    'sidebar_nav_flat_style': True,
    # Save buttons in Tesmus charcoal instead of green; delete stays red.
    'button_classes': {
        'primary': 'btn-primary',
        'secondary': 'btn-outline-primary',
        'info': 'btn-outline-primary',
        'warning': 'btn-warning',
        'danger': 'btn-danger',
        'success': 'btn-primary',
    },
}
