# Generated by Django 5.2.17 on 2026-09-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_message_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessage',
            name='audience_type',
            field=models.CharField(choices=[('church', 'All members'), ('leadership', 'Leadership group'), ('region', 'Members in a region'), ('service_present', 'Members present at a service'), ('service_absent', 'Members absent from a service'), ('visitor_present', 'Visitors present at a service'), ('individual', 'Individual or automated message')], default='individual', max_length=30),
        ),
    ]
