# Generated by Django 5.2.17 on 2026-09-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_alter_smsmessage_audience_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='attempt_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
