# Generated by Django 5.2.17 on 2026-09-03 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('tenants', '0002_church_last_member_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('first_visit_date', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to='tenants.branch')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitors', to='tenants.church')),
                ('converted_to_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_visitor', to='members.member')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to='tenants.region')),
            ],
            options={
                'indexes': [models.Index(fields=['church', 'phone_number'], name='visitors_vi_church__69b486_idx')],
            },
        ),
    ]
