# Generated by Django 5.2.17 on 2026-09-14 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='branch',
        ),
    ]
