# Generated by Django 5.2.17 on 2026-09-21 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_remove_member_branch'),
        ('pastoral', '0001_initial'),
        ('services', '0004_remove_service_branch'),
        ('tenants', '0012_church_absence_alert_after'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pastoralfollowup',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pastoralfollowup',
            name='missed_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Services missed in a row when this follow-up opened.'),
        ),
        migrations.AddField(
            model_name='pastoralfollowup',
            name='pastors',
            field=models.ManyToManyField(blank=True, related_name='pastoral_assignments', to='members.member'),
        ),
        migrations.AddField(
            model_name='pastoralfollowup',
            name='reason',
            field=models.CharField(choices=[('manual', 'Added by hand'), ('missed_services', 'Missed services in a row')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='pastoralfollowup',
            name='trigger_service',
            field=models.ForeignKey(blank=True, help_text='The service whose closing opened this follow-up.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='services.service'),
        ),
        migrations.AlterField(
            model_name='pastoralfollowup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('returned', 'Returned'), ('closed', 'Closed')], default='pending', max_length=15),
        ),
        migrations.AddConstraint(
            model_name='pastoralfollowup',
            constraint=models.UniqueConstraint(condition=models.Q(('reason', 'missed_services'), ('status__in', ['pending', 'in_progress'])), fields=('member',), name='one_open_absence_followup_per_member'),
        ),
    ]
