# Generated by Django 5.2.17 on 2026-09-03 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_church_last_member_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('reference_number', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='tenants.branch')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='tenants.church')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='tenants.region')),
            ],
            options={
                'indexes': [models.Index(fields=['church', 'phone_number'], name='members_mem_church__008aa6_idx')],
                'unique_together': {('church', 'reference_number')},
            },
        ),
    ]
