# Generated by Django 5.2.17 on 2026-09-14 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_ministryrole_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='branch',
        ),
    ]
