# Generated by Django 5.2.17 on 2026-09-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('sms_failed', 'Text messages failed'), ('followup_due', 'Pastoral follow-ups due'), ('member_self_registered', 'New self-registrations'), ('followup_unassigned', 'Follow-ups without a pastor')], max_length=40),
        ),
    ]
