# Generated by Django 5.2.17 on 2026-09-03 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('services', '0001_initial'),
        ('tenants', '0002_church_last_member_sequence'),
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('qr', 'QR'), ('usher', 'Usher'), ('manual', 'Manual')], max_length=10)),
                ('result', models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent')], max_length=10)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='tenants.church')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='members.member')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='services.service')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='visitors.visitor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('service', 'member'), name='unique_member_service_attendance')],
            },
        ),
    ]
