# Generated by Django 5.2.17 on 2026-09-14 10:15

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def copy_member_regions(apps, schema_editor):
    """Existing attendance takes the region its member has today."""
    Attendance = apps.get_model('attendance', 'Attendance')
    Member = apps.get_model('members', 'Member')
    Attendance.objects.filter(region__isnull=True, member__region__isnull=False).update(
        region=Subquery(Member.objects.filter(pk=OuterRef('member_id')).values('region')[:1])
    )


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('members', '0007_alter_ministryrole_options'),
        ('tenants', '0006_church_registration_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='tenants.region'),
        ),
        migrations.RunPython(copy_member_regions, migrations.RunPython.noop),
    ]
